/* Generated by /cygdrive/c/code/atlas/atlas-3.10.1//CONFIG/src/probe_aff.c */
#ifndef ATL_TAFFINITY_H
   #define ATL_TAFFINITY_H

#include <windows.h>
#define ATL_HAS_AFFINITY 10
#define ATL_PAFF_WIN 1
#define ATL_PAFF_LAUNCH 1  /* affinity can be set during thread launch */
#define ATL_AFF_NUMID 2
#define ATL_AFF_IDSTRIDE 1
#define ATL_RANK_IS_PROCESSORID 1 /* good IDs [0,1] */

#endif /* end multiple inclusion guard */
