  /* This file generated by /cygdrive/c/code/atlas/atlas-3.10.1//tune/threads/probe_nthr.c */
#ifndef ATLAS_NTHREADS_H
   #define ATLAS_NTHREADS_H

   #define ATL_NTHREADS 2
   #define ATL_NTHRPOW2 1
   #ifdef ATL_LAUNCHORDER
       static int ATL_launchorder[2] = {0,1};
   #endif

#endif
